# Generated by Django 5.1.5 on 2025-02-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last',
            new_name='last_name',
        ),
    ]
