# Generated by Django 5.1.5 on 2025-02-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_last_account_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_satff',
            new_name='is_staff',
        ),
    ]
